name: Deploy

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest

        steps:
            - name: Print variable 
              run: echo "${{secrets.TOKEN_SECRET}}"

            - name: setup
              uses: actions/setupnode@v4
              with:
                node-version: '18'